.github/workflows/tls.yml
site/app/Api/Presenters/CertificatesPresenter.php
site/app/Tls/CertificateMonitor.php
site/app/Tls/CertificatesApiClient.php
site/config/common.neon
site/config/local.template.neon
site/config/parameters.neon

Issues found after deploying certmonitor (#12) to GitHub Actions.

Certmonitor GitHub actions CLI config

---

site/app/Http/HttpStreamContext.php
site/app/Net/DnsRecord.php
site/app/Net/DnsResolver.php
site/app/Net/Exceptions/DnsGetRecordException.php
site/app/Tls/CertificateGatherer.php
site/app/Tls/CertificateMonitor.php
site/app/Tls/CertificatesApiClient.php
site/config/services.neon

Hostname can have multiple IP addresses (IPv4, IPv6, load balancing) check certs on all of them.
Ref #12

Certmonitor all hostname's IP addreses

---

docs/nginx/common-headers.conf
site/config/common.neon

_So long and thanks for all the fish?_
Fix #20

It has now been removed from all modern browsers

---

site/app/Admin/Presenters/BlogPresenter.php
site/app/Admin/Presenters/templates/Blog/add.latte
site/app/Articles/Articles.php
site/app/Feed/Exports.php
site/app/Form/PostFormFactory.php
site/app/Post/Data.php
site/app/Post/Loader.php
site/app/Post/Post.php
site/app/Training/Dates.php
site/tests/Feed/ExportsTest.phpt
site/tests/php-unix.ini

For example because the post is very private or something. I know some sites syndicate my content, because I put my articles in full into my feed, and that's fine, but I want some posts to be published just on my site.

Blog post can be omitted from RSS exports

---

site/app/Test/TestCaseRunner.php
site/config/tests.neon
site/tests/Application/BootstrapTest.phpt
site/tests/Application/ThemeTest.phpt
site/tests/EasterEgg/NetteCve202015227Test.phpt
site/tests/EasterEgg/WinterIsComingTest.phpt
site/tests/Feed/ExportsTest.phpt
site/tests/Formatter/TexyPhraseHandlerTest.phpt
site/tests/Http/HttpStreamContextTest.phpt
site/tests/Http/SecurityHeadersTest.phpt
site/tests/Pulse/Passwords/RatingTest.phpt
site/tests/Tags/TagsTest.phpt
site/tests/Templating/TemplateFactoryTest.phpt
site/tests/Tls/CertificateFactoryTest.phpt
site/tests/Training/Dates/TrainingDatesFormValidatorTest.phpt
site/tests/Training/Files/TrainingFilesCollectionTest.phpt
site/tests/Training/FormSpamTest.phpt
site/tests/Training/PriceTest.phpt
site/tests/Training/PricesTest.phpt
site/tests/UpcKeys/WiFiKeyTest.phpt
site/tests/Utils/Base64Test.phpt
site/tests/bootstrap.php

Save some `getByType`s when creating test objects with `TestCaseRunner`

---

.github/workflows/composer-vulns.yml
site/composer.json

Requires Composer 2.4 https://blog.packagist.com/composer-2-4/

Run `composer audit` from both `composer test` and GitHub Actions

---

site/app/Pulse/Presenters/templates/@layout.latte
site/app/Www/Presenters/templates/@layout.latte
site/config/common.neon
site/public/www.michalspacek.cz/i/css/humbleicons.css
site/public/www.michalspacek.cz/i/css/screen.css

Extract `.humbleicons` to an extra file and reuse that in Pulse

---

.github/workflows/php.yml
site/app/Test/Http/Cookie.php
site/app/Test/Http/Response.php
site/config/common.neon
site/tests/Application/ThemeTest.phpt

- Adds PHP 8.2 tests to CI
- A few fixes to make the tests pass

Start testing on PHP 8.2

---

site/app/Form/Controls/TrainingControlsFactory.php
site/app/Www/Presenters/templates/@layout.latte
site/public/www.michalspacek.cz/i/js/scripts.js

So I could enable Trusted Types.
For #56

Remove jQuery from www scripts

---

.github/workflows/php.yml
.github/workflows/securitytxt.yml
.github/workflows/tls.yml
docs/nginx/common-php.conf
docs/php/dev-michalspacek.cz.conf
docs/php/prod-michalspacek.cz.conf
site/composer.json
site/composer.lock
site/vendor/composer/ClassLoader.php
site/vendor/composer/autoload_real.php
site/vendor/composer/installed.php
site/vendor/composer/platform_check.php

Upgrade to PHP 8.2

---

.github/workflows/gitleaks.yml

https://github.com/marketplace/actions/gitleaks
Close #73

Try and detect hardcoded secrets with Gitleaks, using Gitleaks-Action

---

site/app/DateTime/DateTimeFormatter.php
site/app/Formatter/TexyPhraseHandler.php
site/app/Post/Post.php
site/app/Tags/Tags.php
site/phpstan.neon

Enabled PHPStan bleeding edge rules because I like the [lie detector feature](https://phpstan.org/blog/phpstan-1-10-comes-with-lie-detector).

PHPStan lie detector

---

site/app/Form/ChangePasswordFormFactory.php

The `passwordrules` attribute is for passwords

---

site/app/Www/Presenters/templates/@layout.latte
site/app/Www/Presenters/templates/Pgp/default.latte
site/public/www.michalspacek.cz/i/js/encryption.js

Don't create `SCRIPT` because that needs `TrustedScriptURL` under Trusted Types.
Close #102

Do not block the page when loading encryption JS but do it easier

---

site/app/Pulse/Presenters/templates/@layout.latte
site/app/Www/Presenters/templates/Pgp/default.latte
site/config/common.neon
site/public/www.michalspacek.cz/i/js/application.js
site/public/www.michalspacek.cz/i/js/scripts.js

Because `const APPLICATION = APPLICATION || {};` throws "Uncaught ReferenceError: Cannot access 'APPLICATION' before initialization".
This is how #106 should have been done.

Make APPLICATION always available

---

site/app/Www/Presenters/templates/Pgp/default.latte

`App` is already available

---

site/app/Admin/Presenters/templates/@layout.latte
site/app/Admin/Presenters/templates/Pulse/passwordsStorages.latte
site/app/Admin/Presenters/templates/Talks/slides.latte
site/app/Admin/Presenters/templates/Trainings/date.latte
site/public/www.michalspacek.cz/i/css/screen.css
site/public/www.michalspacek.cz/i/js/admin.js
site/public/www.michalspacek.cz/i/js/app.js
site/public/www.michalspacek.cz/i/js/pulse.js
site/public/www.michalspacek.cz/i/js/scripts.js

So I can start using Trusted Types in admin too.
Close #98

Remove jQuery from admin

---

site/app/UpcKeys/Presenters/templates/Homepage/default.latte
site/public/www.michalspacek.cz/i/js/upckeys.js

Remove jQuery from upckeys

---

.github/workflows/securitytxt.yml

Not as separate package with apt, this way should be faster.

Add gnupg in setup-php action

---

site/app/Admin/Presenters/templates/Talks/default.latte
site/app/Admin/Presenters/templates/Trainings/common/dateList.latte
site/app/Www/Presenters/CompanyTrainingsPresenter.php
site/app/Www/Presenters/PostPresenter.php
site/app/Www/Presenters/TrainingsPresenter.php

PHPStan latte level 1

---

site/app/Admin/Presenters/templates/Homepage/default.latte
site/app/Admin/Presenters/templates/Interviews/common/interviewForm.latte
site/app/Admin/Presenters/templates/Interviews/default.latte
site/app/Admin/Presenters/templates/Invoices/unpaid.latte
site/app/Admin/Presenters/templates/Talks/common/formVideoThumbnails.latte
site/app/Admin/Presenters/templates/Talks/default.latte
site/app/Admin/Presenters/templates/Trainings/common/dateList.latte
site/app/Admin/Presenters/templates/Trainings/common/reviewForm.latte
site/app/Admin/Presenters/templates/Trainings/default.latte
site/app/Admin/Presenters/templates/Trainings/pastWithPersonalData.latte
site/app/Admin/Presenters/templates/Trainings/review.latte
site/app/Www/Presenters/CompanyTrainingsPresenter.php
site/app/Www/Presenters/PostPresenter.php
site/app/Www/Presenters/TrainingsPresenter.php

Some progress to get to PHPStan for Latte to level 1.
Thanks for the help @lulco!

Prepare for phpstan-latte Level 1

---

site/app/Admin/Presenters/InterviewsPresenter.php
site/app/Admin/Presenters/TalksPresenter.php
site/app/Admin/Presenters/templates/Interviews/common/interviewForm.latte
site/app/Admin/Presenters/templates/Interviews/default.latte
site/app/Admin/Presenters/templates/Interviews/interview.latte
site/app/Admin/Presenters/templates/Pulse/passwordsStorages.latte
site/app/Admin/Presenters/templates/Talks/common/formVideoThumbnails.latte
site/app/Admin/Presenters/templates/Talks/common/talkForm.latte
site/app/Admin/Presenters/templates/Trainings/common/dateList.latte
site/app/Admin/Presenters/templates/Trainings/pastWithPersonalData.latte
site/app/EasterEgg/NetteCve202015227.php
site/app/EasterEgg/NetteCve202015227Rce.php
site/app/EasterEgg/Presenters/NettePresenter.php
site/phpstan-latte-templates.neon
site/tests/EasterEgg/NetteCve202015227Test.phpt

There has been some work done in #128 to get this to phpstan-latte Level 1 but more is needed, it's mostly "might not be defined" errors (only these actually) and they'll take some time I guess.

phpstan-latte Level 1

---

site/app/Pulse/Passwords.php
site/app/Pulse/Passwords/Algorithm.php
site/app/Pulse/Passwords/AlgorithmAttributes.php
site/app/Pulse/Passwords/AlgorithmAttributesFactory.php
site/config/services.neon
site/phpstan-latte-templates.neon
site/tests/Pulse/Passwords/AlgorithmAttributesFactoryTest.phpt
site/tests/Pulse/Passwords/AlgorithmTest.phpt
site/tests/Pulse/Passwords/RatingTest.phpt

This is what should have been done in 5cca31a8361e27417edebac0533de649d0e6f463 as part of `stdClass` removal but I guess I was lazy back then.
Ref #141

Bump PHPStan Latte level to 3

---

site/config/contentsecuritypolicy.neon

Add Trusted Types requirement to other presenters too

---

site/app/Application/Bootstrap.php
site/app/Application/Exceptions/ServerEnvException.php
site/app/Application/Exceptions/ServerEnvNotArrayException.php
site/app/Application/Exceptions/ServerEnvNotFoundException.php
site/app/Application/Exceptions/ServerEnvNotStringException.php
site/app/Application/ServerEnv.php
site/app/Application/WebApplication.php
site/app/Tls/CertificatesApiClient.php
site/bin/certmonitor.php
site/disallowed-calls.neon
site/phpstan-vendor.neon
site/tests/Application/ServerEnvTest.phpt

Replace `$_SERVER` with a service with stricter types

---

site/app/Articles/Articles.php
site/app/Articles/Blog/BlogPost.php
site/app/Articles/Blog/BlogPosts.php
site/app/CompanyInfo/Exceptions/CompanyInfoException.php
site/app/CompanyInfo/Info.php
site/app/CompanyInfo/RegisterUz.php
site/app/Formatter/Exceptions/UnexpectedHandlerInvocationReturnType.php
site/app/Formatter/TexyFormatter.php
site/app/Formatter/TexyPhraseHandler.php
site/app/Http/Redirections.php
site/app/Pulse/Passwords.php
site/app/Pulse/Passwords/StorageRegistryFactory.php
site/app/Pulse/SpecificSite.php
site/app/Tags/Tags.php
site/app/Templating/Filters.php
site/app/Training/Applications.php
site/app/Training/Trainings.php
site/app/Utils/Exceptions/JsonItemNotStringException.php
site/app/Utils/Exceptions/JsonItemNotStructureException.php
site/app/Utils/Exceptions/JsonItemsNotArrayException.php
site/app/Utils/JsonUtils.php
site/config/services.neon
site/tests/Articles/ArticlesTest.phpt
site/tests/Http/RedirectionsTest.phpt
site/tests/Templating/FiltersTest.phpt
site/tests/Training/ApplicationsTest.phpt
site/tests/Training/TrainingsTest.phpt
site/tests/Utils/JsonUtilsTest.phpt

From 25 errors down to just 6.
For #147

PHPStan level 9 progress part 2

---

site/app/Application/AppRequest.php
site/app/Application/Exceptions/NoOriginalRequestException.php
site/app/Www/Presenters/BasePresenter.php
site/app/Www/Presenters/ErrorPresenter.php
site/tests/Application/AppRequestTest.phpt

Return correct exception when no original request has been found

---

.github/workflows/php-latte.yml
.github/workflows/php.yml
.github/workflows/securitytxt.yml
.github/workflows/tls.yml

Start testing on PHP 8.3

---

site/app/Interviews/Interviews.php
site/app/Talks/Talks.php
site/app/Training/Reviews.php
site/app/Www/Presenters/CompanyTrainingsPresenter.php
site/app/Www/Presenters/TrainingsPresenter.php
site/phpstan.neon

From 6 errors in #156 down to zero, nil, nothing, nada.
And back to _max_ level which is 9 currently, see the [PHPStan config](https://github.com/phpstan/phpstan-src/blob/0d6755b37d986a3803cbb3b149f4af60e42c0829/conf/config.levelmax.neon#L1-L2).
Close #147

PHPStan level max/9

---

site/app/Application/AppRequest.php
site/tests/Application/AppRequestTest.phpt

Sometimes the exception coming to error presenters is an `Error`, not just `Exception`

---

site/app/Admin/Presenters/ReviewsPresenter.php
site/app/Admin/Presenters/TalksPresenter.php
site/app/Admin/Presenters/templates/Pulse/passwordsStorages.latte
site/app/Admin/Presenters/templates/Talks/slides.latte
site/phpstan-latte-templates.neon

* Change action `$param` type to int where possible
* Work around efabrica-team/phpstan-latte#396
Ref #141

PHPStan Latte level 5

---

README.md

Show PHPStan Latte badge

---

site/phpstan-latte-templates.neon

efabrica-team/phpstan-latte#400 is probably better and more specific to this problem, add it too.

Add better link to ignored errors

---

site/app/Articles/articleHeaderIcons.latte
site/app/Articles/articleSummary.latte
site/phpstan-latte-templates.neon

Enable bleeding edge rules for templates too

---

site/app/Admin/Presenters/BlogPresenter.php

Add header icons back to blog post preview

---

site/app/Talks/TalksList.php
site/app/Talks/TalksListFactory.php
site/app/Talks/talksList.latte
site/app/Www/Presenters/HomepagePresenter.php
site/app/Www/Presenters/TalksPresenter.php
site/app/Www/Presenters/templates/Homepage/default.latte
site/app/Www/Presenters/templates/Talks/common/itemTalk.latte
site/app/Www/Presenters/templates/Talks/default.latte
site/config/services.neon

Here's me predicting this will be useful in the very near future.

Replace an include with TalksList component

---

.github/workflows/tls.yml

Use the new testssl action version to support Node16

---

site/app/Form/TrainingApplicationFormFactory.php
site/app/Form/TrainingApplicationPreliminaryFormFactory.php
site/app/Training/FormSpam.php
site/app/lang/messages.cs_CZ.neon
site/app/lang/messages.en_US.neon
site/tests/Training/FormSpamTest.phpt

Way too many log lines I don't read anyway and the chance of a false positive is quite low.

Don't log spammy training applications

---

site/app/Www/Presenters/templates/@layout.latte
site/app/Www/Presenters/templates/Contact/default.latte
site/app/lang/messages.cs_CZ.neon
site/app/lang/messages.en_US.neon

Including the `rel=me` verification attribute, see https://infosec.exchange/settings/verification

Add Mastodon links, my handle is `@spazef0rze@infosec.exchange`

---

site/app/Training/ApplicationForm/TrainingApplicationFormSuccess.php
site/tests/Training/ApplicationForm/TrainingApplicationFormSuccessTest.phpt

Changed in commit 8a9663861cdecbb3e83c5382edbe58dd367b350b but in 7a2d26e9359291248b9bfe7a5008b4cf45c4938a I forgot to change it here.

With a single training date available, there's no `trainingId` field anywhere in the form

---

site/app/Admin/Presenters/TrainingsPresenter.php

Use an existing TrainingApplication object

---

site/app/Admin/Presenters/templates/Pulse/passwordsStorages.latte

The field was renamed in 9fda4ddb2edeb26d16540d4339be8824b5d78950 in #176 but I missed this

Use correct field name for Pulse Passwords algorithm

---

site/app/Application/CriticalCss.php
site/app/Application/CriticalCssFactory.php
site/app/Application/criticalCss.latte
site/app/Pulse/Presenters/templates/@layout.latte
site/app/Www/Presenters/BasePresenter.php
site/app/Www/Presenters/templates/@layout.latte
site/config/common.neon
site/config/services.neon
site/public/www.michalspacek.cz/i/css/humbleicons.css
site/public/www.michalspacek.cz/i/css/pulse/screen.css

Otherwise if there's no CSS loaded for whatever reason, the icons are full-width making them really huge.

Critical CSS as a component

---

.github/dependabot.yml

Keep my GitHub actions up to date with Dependabot

---

site/app/CompanyInfo/CompanyRegisterAres.php

They now probably add it themselves.
Followup to #225

The country code in the tax id has started to be duplicated

---

site/app/Application/Theme.php
site/app/DateTime/DateTime.php
site/app/Http/Cookies/CookieDescription.php
site/app/Http/Cookies/CookieDescriptions.php
site/app/Http/Cookies/CookieName.php
site/app/Http/Cookies/Cookies.php
site/app/Http/HttpInput.php
site/app/User/Manager.php
site/app/Www/Presenters/CookiesPresenter.php
site/app/Www/Presenters/templates/@layout.latte
site/app/Www/Presenters/templates/Cookies/default.latte
site/app/lang/messages.cs_CZ.neon
site/app/lang/messages.en_US.neon
site/config/parameters.neon
site/config/presenters.neon
site/config/routes.neon
site/config/services.neon
site/disallowed-calls.neon
site/phpstan-vendor.neon
site/psalm.xml
site/public/www.michalspacek.cz/i/css/screen.css
site/tests/DateTime/DateTimeTest.phpt
site/tests/Http/Cookies/CookieDescriptionsTest.phpt
site/tests/Http/Cookies/CookiesTest.phpt
site/tests/Http/HttpInputTest.phpt

The list is generated automatically, and except the framework cookies, you can't create a cookie without adding an item into the `CookieName` enum. Which means that a test can be written, and was written, that makes sure that all cookies are described.
Have to admit this is mostly a flex 😁

Add cookies page

---

site/app/Templating/Filters.php
site/tests/Templating/TemplateFactoryTest.phpt

Blocked by
- efabrica-team/phpstan-latte#435

Latte filters first class callable

---

site/app/CompanyInfo/CompanyRegisterAres.php

This reverts commit 8524ef3e57e2f6806f5a6142f9168cd9dd9a87b1 from #244 which was a fix for #242

Revert "I don't understand why but for this 'res' source, the country code is returned as "1", yes a string, instead of "cz", so let's deal with that"

---

.github/workflows/php-latte.yml
.github/workflows/php-tester-include-skipped.yml
.github/workflows/php.yml
.github/workflows/securitytxt.yml
.github/workflows/tls.yml
conf/nginx/common-php.conf
conf/php/dev-michalspacek.cz.conf
conf/php/prod-michalspacek.cz.conf
site/composer.json
site/composer.lock
site/vendor/composer/installed.php
site/vendor/composer/platform_check.php

- Stop testing on PHP 8.2
- Update nginx config
- Update PHP FPM pool config
- Update version constraint in `composer.json` and regenerate the generated files
Close #159

Upgrade to PHP 8.3

---

conf/php/dev-michalspacek.cz.conf
site/app/Application/Bootstrap.php
site/composer.json
site/composer.lock
site/tests/Application/BootstrapTest.phpt
site/vendor/composer/installed.php

Run PHP under spaze/spaze so that PHP-created files owner matches the OS-created files owner.
This reverts commits f5551ef & c6ee81d from #263.

Get the WSL temp dirs mess right eventually

---

site/public/www.michalspacek.cz/i/js/app.js
site/public/www.michalspacek.cz/i/js/pulse.js

Add `App.nextElementSiblings` to get all, you know, next element siblings, and remove `hidden` class from all next siblings in password storage history 
Close #280

Next element siblings

---

site/config/services.neon

`Pulse` classes use separate database so `TypedDatabase` used in those must also use different database

---

site/app/Www/Presenters/templates/Who/default.latte
site/app/lang/messages.cs_CZ.neon
site/app/lang/messages.en_US.neon

I've left Report URI at the end of 2022, time to update the Who page and add Shoptet

Bye Report URI

---

site/app/Admin/Presenters/InfoPresenter.php
site/app/Application/SanitizedPhpInfo.php
site/config/services.neon
site/disallowed-calls.neon

Even though they won't be displayed there on the current URL
Ref #288

Sanitize more cookies in `phpinfo()`

---

site/app/Test/Training/TrainingFilesNullStorage.php
site/app/Training/Files/TrainingFilesDownload.php
site/config/services.neon
site/config/tests.neon
site/tests/Training/Files/TrainingFilesDownloadTest.phpt
site/tests/Training/Files/TrainingFilesStorageTest.phpt
site/tests/php-unix.ini

I think this is a regression introduced in #209 or something like that.

Check session data is complete before attempting to download a file

---

.github/workflows/scorecard.yml

See
https://github.com/marketplace/actions/ossf-scorecard-action
https://securityscorecards.dev/

Add the OpenSSF Scorecards GitHub Action

---

.github/dependabot.yml

Allow both direct and indirect Dependabot updates for all packages

---

SECURITY.md

And the text should also contain specific text as per https://github.com/spaze/michalspacek.cz/security/code-scanning/64
Close #324 again
Follow-up to #325

Seems like there should be this link for the file to be accepted

---

site/app/Form/InterviewFormFactory.php
site/app/Form/TalkFormFactory.php
site/app/Media/VideoThumbnailFileUploads.php
site/app/Media/VideoThumbnails.php

Resolve `PHP Warning: Undefined property: Nette\Utils\ArrayHash::$removeVideoThumbnail`
Introduced in d700c61c02c53a6694a4f22f704faf98e5fbe0e4 #275

The form value property may not exist when saving the talk or interview

---

.github/workflows/codeql.yml
.github/workflows/gitleaks.yml
.github/workflows/php-latte.yml
.github/workflows/php-tester-include-skipped.yml
.github/workflows/php.yml
.github/workflows/scorecard.yml
.github/workflows/securitytxt.yml
.github/workflows/tls.yml

Bump
- shivammathur/setup-php from 2.30.4 to 2.30.5
- gitleaks/gitleaks-action from 2.3.4 to 2.3.6
- github/codeql-action from 3.25.6 to 3.25.7

Update GitHub Actions

---

site/app/Formatter/Placeholders/FetchMetadataTexyFormatterPlaceholder.php
site/app/lang/messages.cs_CZ.neon
site/app/lang/messages.en_US.neon
site/tests/Formatter/TexyFormatterTest.phpt

Show a text instead of the value when a fetch metadata header wasn't sent

---

site/app/Http/FetchMetadata/ResourceIsolationPolicy.php
site/tests/Http/FetchMetadata/ResourceIsolationPolicyTest.phpt

Add more Fetch Metadata Resource Isolation Policy logging

---

site/app/Http/FetchMetadata/ResourceIsolationPolicy.php
site/tests/Http/FetchMetadata/ResourceIsolationPolicyTest.phpt

Log the full request URL in Resource Isolation Policy Logging

---

app/bin/check-file-patterns.sh

Find app files in the app dir, not src

---

app/phpstan-vendor.neon

Remove path from `excludePaths` that doesn't exist anymore

---

README.md

The tests have been disabled in #428.

Remove PHPStan Latte templates tests badge

---

app/config/local.template.neon

That's what aiosmtpd uses as configured in https://github.com/spaze/home/issues/1

Use 2525 for sending emails in local dev env

---

app/src/Www/Presenters/BasePresenter.php

This reverts commit 7d8458d021c68b6bc642ddafa87101e2e5a7662b of #17.
> Maybe this is the root cause [php/php-src#8218](https://github.com/php/php-src/issues/8218), need to re-check and possibly revert [#17](https://github.com/spaze/michalspacek.cz/pull/17) if that's the case.
-- https://github.com/spaze/michalspacek.cz/issues/16#issuecomment-1130229144

Revert "Don't gzip HTTP 304s, they have no response bodies anyway"

---

app/src/Www/Presenters/BasePresenter.php

This reverts commit da6917f8621e74e8930567f967ee2990e1e0b05a of #545 which reverted #17.
Close #16 again.

Reapply "Don't gzip HTTP 304s, they have no response bodies anyway"

---

app/config/tests.neon
app/src/Admin/Presenters/HomepagePresenter.php
app/src/Tls/CertificateFactory.php
app/src/Tls/Certificates.php
app/tests/Tls/CertificatesTest.phpt

Plus some tests.
Follow-up to #556

Memoize the newest certs, makes the presenter code shorter

---

app/src/Presentation/Pulse/Error/ErrorPresenter.php

Correct path of the `.html` file, it has been moved recently

---

conf/letsgetacert/michal-spacek.cz.cnf
conf/nginx/prod-https-michal-spacek.cz.conf

Remove michal-spacek letsgetacert config, the cert will be managed by Certbot directly

---

conf/letsgetacert/michalspacek.cz.cnf
conf/nginx/prod-https-michalspacek.cz.conf

Remove michalspacek letsgetacert config, the cert will be managed by Certbot directly

---

app/public/www.michalspacek.cz/i/css/screen.css
app/src/Tls/CertificatesList/tlsCertificatesList.latte

Put cert SANs to a new line

---

app/config/contentsecuritypolicy.neon

See https://scotthelme.co.uk/capture-javascript-integrity-metadata-using-csp/

Add integrity metadata to CSP reports

---

app/config/contentsecuritypolicy.neon

See https://scotthelme.co.uk/capture-javascript-integrity-metadata-using-csp/
Follow-up to #592

Add CSP integrity reports to CSS/`style-src` as well
