spaze/michalspacek.cz

.github/workflows/php.yml
site/app/CompanyInfo/Ares.php
site/app/Post/Post.php
site/app/Training/Applications.php
site/app/Training/Files.php
site/app/Training/Price.php
site/app/Training/Reviews.php
site/app/Training/Statuses.php
site/app/UpcKeys/Technicolor.php
site/app/Www/Presenters/PostPresenter.php
site/composer.json

Run tests on PHP 8.0 before switching to it.
Need to use shivammathur/setup-php@v2 because ubuntu-latest will use Ubuntu 20.04 soon and only PHP 7.4 will be supported https://github.com/actions/virtual-environments/issues/1816

Run tests on PHP 8.0

---

site/composer.json
site/composer.lock
site/disallowed-calls.neon
site/phpstan-vendor.neon
site/phpstan.neon
site/vendor/composer/InstalledVersions.php
site/vendor/composer/installed.php

Use spaze/phpstan-disallowed-calls to scan for disallowed calls in `vendor/` too. Just to make sure there are no known dangerous calls in dependencies.
Dev dependencies should be deleted in production (that's what spaze/stupid-git-deploy does by scanning and deleting `composer.json`'s `require-dev`).
Not fully convinced this is a good or useful idea but *ví vil sí*.

Scan for disallowed calls in vendor dir

---

site/config/contentsecuritypolicy.neon

For example jQuery 3.x is not ready https://github.com/jquery/jquery/issues/4409
Partially reverts #8

Remove trusted types requirement, it generates a lot of reports

---

.github/workflows/composer-vulns.yml
.github/workflows/php.yml

Runs tests in parallel for speedup. Downside is that `matrix.php-version` has to be specified multiple times but guess that's acceptable. Further speedup by using PHPStan and PHPCS result caches.
Run Symfony security checker also every hour because if I don't push soon enough, I might miss the *memo*.

GitHub Actions speedup

---

site/composer.json
site/composer.lock
site/vendor/composer/ClassLoader.php
site/vendor/composer/autoload_real.php
site/vendor/composer/installed.json
site/vendor/composer/installed.php

Required by #12 for normal non-dev operations too and must be in `require`, not in `require-dev` otherwise it gets deleted by [stupid-git-deploy](https://github.com/spaze/stupid-git-deploy).

php-console-color required

---

.github/workflows/tls.yml
site/app/Application/Bootstrap.php
site/app/Tls/CertificatesApiClient.php

- Certs are in `certificates` field in the API response  (#14 commit 2b0c36fc47b1f554ae27a5995ee87e76a17000fb)
- Force colors when running in GitHub Actions
Required for #12.

Certmonitor, correct JSON field, always colors

---

site/app/Www/Presenters/BasePresenter.php
site/phpstan.neon

But compressing all responses including 304s, makes nginx log "upstream sent more data than specified in "Content-Length" header while reading upstream". Compression is re-enabled only if the AbortException wasn't thrown in \Nette\Application\UI\Presenter::lastModified.
Fix #16 (this feels like the best fix because to me it seems like an nginx issue though I may be wrong)

Don't gzip HTTP 304s, they have no response bodies anyway

---

.github/workflows/tls.yml
site/app/Tls/CertificateGatherer.php
site/app/Tls/CertificateMonitor.php
site/bin/certmonitor.php

Don't certmonitor IPv6 addresses . Because it seems GitHub Actions don't support IPv6 actions/virtual-environments#668
But that's fine because although my sites run on IPv6 too, they all run the same TLS config on both IPv4 and IPv6.
Ref #12

No IPv6 for old men (and for Cert monitor_

---

site/composer.json
site/composer.lock
site/vendor/composer/installed.php

Reverts part of #4, the dev dependencies would be deleted based on their presence in `installed.php`. not `composer.json`, by https://github.com/spaze/stupid-git-deploy/pull/2

Remove indirect/"second row" dev dependencies from `composer.json`

---

site/tests/Application/BootstrapTest.phpt
site/tests/php-unix.ini

I'm still not fully convinced whether this is a good idea or whether the test makes sense and/or is written correctly, but let's see.
This is an [example of a failing test](https://github.com/spaze/michalspacek.cz/runs/7660844853?check_suite_focus=true):
```
Run composer --working-dir=site tester
> vendor/nette/tester/src/tester -c tests/php-unix.ini --colors 1 --coverage temp/coverage.html --coverage-src app/ tests/
_____ ___  ___ _____ ___  ___
|_   _/ __)( __/_   _/ __)| _ )
|_| \___ /___) |_| \___ |_|_\  v2.4.2
Code coverage by PCOV: /home/runner/work/michalspacek.cz/michalspacek.cz/site/temp/coverage.html
PHP 8.1.8 (cli) | php -n -c /home/runner/work/michalspacek.cz/michalspacek.cz/site/tests/php-unix.ini -d pcov.directory=/home/runner/work/michalspacek.cz/michalspacek.cz/site/app | …
```

Test the DI container is built correctly in Bootstrap

---

site/app/Application/Bootstrap.php

If not set, the default is used and the default is calculated as a directory in which the executed test file is stored. So the `wwwDir` is different for each test file executed which results in many containers (one per dir) being created when running the full test suite which slows it down.
Follow-up to #27

Set `wwwDir` param for tests, too

---

.github/workflows/composer-vulns.yml

There's a v3 tag not a release (only v2 release) and so the GitHub Actions page offers v2 only and I noticed only now
- The tag: https://github.com/symfonycorp/security-checker-action/releases/tag/v3
- Symfony issue https://github.com/symfonycorp/security-checker-action/issues/6
v2 [stopped working](https://github.com/spaze/michalspacek.cz/runs/8140472020?check_suite_focus=true) due to
> Error response from daemon: pull access denied for symfonycorp/cli, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Use v3 of Symfony Security Checker

---

.github/workflows/securitytxt.yml

The IPv6 support https://github.com/spaze/security-txt/issues/2
Had to do something similar for certmonitor in 5c9cbcddeb12a2acf21bce0e779c5cc96af469aa

spaze/security-txt got IPv6 support, unlike GitHub Actions

---

.github/workflows/composer-vulns.yml
.github/workflows/php.yml
.github/workflows/tls.yml

1. Upgrade to `@v3` actions to use Node.js 16 and remove deprecation warnings about Node.js 12, see [docs](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
2. Replace `::set-output` in `phpstan` and `phpcs` jobs with environment file, see [docs](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
Fix #37

GitHub Actions actions upgrade

---

docs/nginx/common-https.conf

Chrome was the only browser that has supported the header, and it has dropped its support now in 107:
- https://chromestatus.com/feature/6244547273687040
- https://chromium.googlesource.com/devtools/devtools-frontend.git/+/c7b92aac4dcb53c59d056711e75b80a6949ae87e%5E%21/
Close #33

Remove `Expect-CT` header

---

.github/workflows/securitytxt.yml
.github/workflows/tls.yml

PHP 8.2 is not available in Ubuntu (yet, not even sure whether and if it will ever be in `ubuntu-latest`) so can't be setup with `update-alternatives`.
Followup to #58
For #53

Setup PHP 8.2 with the setup-php action

---

.github/workflows/php.yml

This [option](https://github.com/shivammathur/setup-php/#signal_strength-coverage-support) might not be intended for Tester directly but indirectly it may work by installing the pcov extension.
Follow-up to #49

Use pcov for code coverage for tester

---

site/app/Application/Bootstrap.php
site/composer.json
site/composer.lock
site/vendor/composer/installed.php

Removing it mostly because of https://github.com/efabrica-team/phpstan-latte/issues/229 (and because I don't need it, of course). It's still required by nette/di so the package itself stays.

I think I can just stop using nette/robot-loader and use Composer autoloader only

---

.gitleaks.toml
.gitleaksignore

This adds custom config for the Gitleaks action added in #73. Currently, the action uses slightly older version of Gitleaks so there might be some differences in what it detects.
The new "generic-api-key-extra-keywords" rule is the same as the "Generic API Key" rule from the default config file except it has a lower entropy and adds a few more keywords ("dev", "prod") to both the "regex" and "keywords" fields.
`.gitleaksignore` ignores items that have either been rotated or are just examples

Add Gitleaks config

---

.github/workflows/gitleaks.yml

See the source for the "latest" version logic https://github.com/gitleaks/gitleaks-action/blob/1f2d10fb689bc07a5f56f48d6db61f5bbbe772fa/src/index.js#L134-L135
See this PR that hard-codes the version for reasons why https://github.com/gitleaks/gitleaks-action/pull/78
This PR adds the missing documentation https://github.com/gitleaks/gitleaks-action/pull/109

Use the latest Gitleaks version in the action

---

site/app/PhpStan/presenterFactory.php
site/phpstan-latte-templates.neon

- Use presenter factory instead of app mapping config
Close #81
- Early terminating calls like redirectPermanent should now be detected automatically

Remove PHPStan Latte legacy config

---

conf/nginx/dev-php.conf
conf/php/dev-michalspacek.cz.conf
site/app/Application/Bootstrap.php

Start using WSL for local dev.
But using `/mnt/c/` is veeeeeeeeeery, veeeeeeeeeeeeeeeeery slooooooow. To partially speed things up (so nginx won't timeout, the bar is really low), the temp dir is moved to WSL filesystem.
This brings only a very, very <sub>small</sub> performance improvement, but at least something.
See microsoft/WSL#9412 for some good news which should hopefully be soon available in WSL.
`/tmp/michalspacek.cz` is managed by `tmpfiles.d`:
```
$ cat /etc/tmpfiles.d/tmp-michalspacek.cz.conf
d /tmp/michalspacek.cz 0777 www-data www-data -
```

WSL for local dev

---

conf/nginx/common-_.michalspacek.cz.conf
conf/nginx/common-admin.michalspacek.cz.conf
conf/nginx/common-app.conf
site/app/Admin/Presenters/WellKnownPresenter.php
site/app/Application/RouterFactory.php

`<admin>/.well-known/change-password` will now redirect to the page where you, or actually just I, can change my password. This is for a nicer integration with 1Password.
The redirect is done in Nette so that I can redirect to `presenter:action` and not a URL. If the redirect would be done in server config, then it's one more place to change if the URL changes. Also not added as a one-way route to Nette because the redirection should be a temporary redirect while the one-way route redirect is a permanent one.
See the spec here https://www.w3.org/TR/change-password-url/

Add well-known URL for changing passwords in admin

---

site/app/Form/ChangePasswordFormFactory.php
site/app/Form/Controls/FormControlsFactory.php
site/app/User/Exceptions/IdentityNotSimpleIdentityException.php
site/app/User/Manager.php

Well, I'm the only one using the login forms on this site but still wanted to try these.
- Raise min length to 15 chars
- Help password managers understand the form fields
- Indicate which account is the password being changed for
- Tell 1Password to generate a bit longer+stronger password by default
TIL the `passwordrules` attribute thanks to this great @scotthelme's blog post https://scotthelme.co.uk/boosting-account-security-pwned-passwords-and-zxcvbn/
Here are some helpful links:
- [Design your website to work best with 1Password](https://developer.1password.com/docs/web/compatible-website-design/)
- [Password Rules Validation Tool](https://developer.apple.com/password-rules/) by Apple, apparently supported in Safari [since 2018 (Safari …

Password forms improvements

---

site/app/UpcKeys/UpcKeys.php

As documented in https://doc.nette.org/en/dependency-injection/autowiring#toc-collection-of-services
It was nice to have the type definition in the signature but it stopped working.
Close #94

Use a regular array for services collection, not variadics

---

site/config/contentsecuritypolicy.neon

Previously, I've enabled Trusted Types for the whole site (#8) and had to roll back (#10) but since then have removed jQuery from www scripts (#57) so this should be fine.
For #56

CSPRO Trusted Types for `www` only

---

site/app/Pulse/Presenters/templates/@layout.latte
site/public/www.michalspacek.cz/i/js/pulse.js

Losing the `slideToggle()` animation but that's fine because doing it in vanilla JS seems a bit harder than it should be.
Close #99

Remove jQuery from Pulse

---

site/app/Pulse/Presenters/templates/@layout.latte
site/app/Www/Presenters/templates/Pgp/default.latte
site/config/common.neon
site/public/www.michalspacek.cz/i/js/encryption.js
site/public/www.michalspacek.cz/i/js/onload.js
site/public/www.michalspacek.cz/i/js/pulse.js
site/public/www.michalspacek.cz/i/js/scripts.js

Sometimes, the HTML is loaded quicker than the JS is executed and the handlers/event listeners will not be added.
This is what happened in Pulse after #99.

Add event handlers even when the HTML is already loaded

---

site/app/Pulse/Presenters/templates/@layout.latte
site/app/Www/Presenters/templates/@layout.latte
site/app/Www/Presenters/templates/Pgp/default.latte
site/config/common.neon
site/public/www.michalspacek.cz/i/js/admin.js
site/public/www.michalspacek.cz/i/js/app.js
site/public/www.michalspacek.cz/i/js/encryption.js
site/public/www.michalspacek.cz/i/js/pulse.js
site/public/www.michalspacek.cz/i/js/remove-fbclid.js
site/public/www.michalspacek.cz/i/js/scripts.js
site/public/www.michalspacek.cz/i/js/upckeys.js

And use wherever needed.
I've realized APPLICATION means a training application, not the application as in app, the code. Obviously, that's confusing.
So let's have App as a namespace for the whole app.

Let's rename `APPLICATION` to `App` only

---

site/app/EasterEgg/FourOhFourButFound.php
site/app/EasterEgg/templates/etcPasswd.html
site/app/Test/Http/Request.php
site/app/Www/Presenters/ErrorPresenter.php
site/config/services.neon
site/tests/EasterEgg/FourOhFourButFoundTest.phpt

This is to satisfy some scanners looking for one. I mean, it's Easter, after all.
The `FourOhFourButFound` class could be marked as `readonly` but the code sniffer doesn't yet support readonly classes, see squizlabs/PHP_CodeSniffer#3727.

Serve *a* `/etc/passwd` if requested

---

site/bin/xmllint.sh

But not always, only when the installation has already failed, to save some time.
Because linter job has been failing due to 404:
```
04/24 15:17:09 [NOTICE] Downloading 1 item(s)
04/24 15:17:09 [ERROR] CUID#7 - Download aborted. URI=http://azure.archive.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2-utils_2.9.13%2bdfsg-1ubuntu0.2_amd64.deb
Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://azure.archive.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2-utils_2.9.13%2bdfsg-1ubuntu0.2_amd64.deb
-> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found
04/24 15:17:09 [NOTICE] Download GID#95494fc88056d070 not complete: /var/cache/apt/apt-fast/libxml2-utils_2.9.13+dfsg-1ubuntu0.2_amd64.deb
```
([source](https://github.com/spaze/michalspacek.cz/actions/runs/4788050621/jobs/85 …

Download fresh package information before installing `xmllint`

---

site/public/www.michalspacek.cz/i/js/admin.js
site/public/www.michalspacek.cz/i/js/app.js

When the listener is added to an element, it is stored into a property (array) on the element so it can be read later when cloning and added to the cloned element.
As inspired by jQuery's clone itself
https://github.com/jquery/jquery/blob/89ef81f86f8f371154e9fd3173be5fb57cb72d5e/src/manipulation.js#L38
https://github.com/jquery/jquery/blob/89ef81f86f8f371154e9fd3173be5fb57cb72d5e/src/manipulation.js#L96

JS `cloneNode` to copy event handlers too

---

site/app/Application/WindowsSubsystemForLinux.php
site/app/Talks/Talks.php
site/config/services.neon

Let's ignore the exception when running on WSL then. `tmpName` will not be updated in `$replace->move` because the exception will be thrown before, so have to `getImageSize()` before moving it.
It's very weird and I don't like this but if it's stupid and it works, it's not stupid.

Trying to move_uploaded_file under my WSL (files in Windows) says "Unable to move" even when the file is actually moved

---

site/app/Application/Bootstrap.php
site/app/Application/LocaleLinkGenerator.php
site/app/Formatter/TexyPhraseHandler.php
site/app/Test/NoOpTranslator.php
site/config/tests.neon
site/tests/Application/LocaleLinkGeneratorTest.phpt
site/tests/Formatter/TexyPhraseHandlerTest.phpt

Previous incarnation in e9cc329 didn't really work as the `$locale` parameter was used only for training URLs/actions, not generally.

Proper support `link-en_US:` links in Texy with explicitly specified locale

---

.github/workflows/php-latte.yml
.github/workflows/php.yml
site/Makefile
site/app/Makefile/Exceptions/MakefileContainsRealTargetsException.php
site/app/Makefile/Exceptions/MakefileException.php
site/app/Makefile/Exceptions/MakefileNotFoundException.php
site/app/Makefile/Makefile.php
site/bin/check-makefile.php
site/composer.json
site/config/services.neon
site/tests/Makefile/MakefileTest.phpt
site/vendor/composer/installed.php

Replace composer scripts with `Makefile`. The execution is marginally faster now, also adding a script doesn't require `composer.json` modifications.
All targets in the `Makefile` are also tested to make sure they're phony (listed in `.PHONY` special target).
A phony target is one that runs its recipe even if a file with the target's name already exists. I want all targets to be phony in case a file of the target's name suddenly appears which would prevent the recipe (and the test the recipe runs) to be executed.
Another option would be to check existing files whether they're not of the same name as the target names. Such check would need to run early enough before all tests.

`Makefile`

---

site/config/contentsecuritypolicy.neon

Require Trusted Types using an enforcing CSP, not report-only & disallows creating any Trusted Type policy.
Close #56

Enable Trusted Types

---

site/app/Http/SecurityHeaders.php
site/tests/Http/SecurityHeadersTest.phpt

Extending it turned out to be a bit more difficult so `ErrorGenericPresenter`s get a default CSP config even if it should be a specific config, which seems fine.

`getAction()` is defined on `Ui\Presenter` only but generic error presenters do not extend it

---

.github/workflows/securitytxt.yml

Added in #161
For #159
The setup-php log:
```
Run shivammathur/setup-php@v2
with:
coverage: none
php-version: 8.3
extensions: gnupg
ini-file: production
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh
==> Setup PHP
✓ PHP Installed PHP 8.3.0-dev (78d98e50c4c051de0aa1af8da51b552135dc569d)
==> Setup Extensions
✗ gnupg Could not install gnupg on PHP 8.3.0-dev
```

Don't run the security.txt check on PHP 8.3, ext-gnupg is not yet available

---

site/app/Articles/Blog/BlogPost.php

Another way to fix it would be to set the property to an empty array in `PostFormFactory::buildPost()`.
Close #169

Blog post edits may be accessed without being previously set

---

site/phpstan-latte-templates.neon

Oh look this was easy 😅
Ref #141

Bump to PHPStan Latte level 6

---

site/app/Admin/Presenters/templates/Blog/default.latte
site/app/Admin/Presenters/templates/Trainings/application.latte
site/app/Articles/articleHeaderIcons.latte
site/app/Form/InterviewFormFactory.php
site/app/Interviews/Interview.php
site/app/Interviews/Interviews.php
site/app/Training/Discontinued/DiscontinuedTrainings.php
site/app/Www/Presenters/CompanyTrainingsPresenter.php
site/app/Www/Presenters/TrainingsPresenter.php
site/app/Www/Presenters/templates/Talks/common/videoThumbnail.latte
site/app/Www/Presenters/templates/Talks/talk.latte
site/app/Www/Presenters/templates/Trainings/training.latte
site/phpstan-latte-templates.neon
site/tests/Interviews/InterviewsTest.phpt
site/tests/Training/Discontinued/DiscontinuedTrainingsTest.phpt

- Interview source name & href are always filled, no need to have them nullable
- Make sure nullable values have a value when doing something with them
Ref #141

PHPStan Latte level 8

---

site/app/Training/DateList/UpcomingTrainingDatesList.php
site/app/Training/DateList/UpcomingTrainingDatesListFactory.php
site/app/Www/Presenters/HomepagePresenter.php
site/app/Www/Presenters/TrainingsPresenter.php
site/app/Www/Presenters/VenuesPresenter.php
site/app/Www/Presenters/templates/Venues/venue.latte

This was a regression introduced in #143 in commit f0fc546 when I've converted included pages to a component and forgot there's no variable anymore. They were right, `empty()` considered harmful.

Display trainings on a venue page again

---

site/app/Www/Presenters/templates/CompanyTrainings/training.latte

Regression introduced in #179 commit dcb4c384a41fa61659bca1e41bc8358368d6ffab because previously `$name` was the action.

Pass a training action, not a name

---

site/app/Www/Presenters/TrainingsPresenter.php

Regression introduced in #180 commit c455d80c30ea5532b4074b013d81d179863bc046

`$trainingAction` is not always initialized like in the default action

---

site/app/Articles/Articles.php
site/app/Articles/Blog/BlogPostLoader.php
site/app/Articles/Blog/BlogPostLocaleUrls.php
site/app/Articles/Blog/BlogPosts.php

Column `id_blog_post_locale` has been renamed to `id_locale` only.
SQL queries:
```sql
ALTER TABLE `blog_post_locales` RENAME TO `locales`;
ALTER TABLE `locales` CHANGE `id_blog_post_locale` `id_locale` int unsigned NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `locales` COLLATE 'utf8mb4_general_ci';
```

Rename `blog_post_locales` table and columns to more general `locales`

---

site/app/Www/Presenters/TalksPresenter.php

Because `$this` ones are overwritten.
This was working before in #196 but I broke it in a12a6cb03e81e3a8849275838f98508506cb0a4c by adding `getLocaleLinkAction()` and `getLocaleLinkParams()`.

Have to use parent classes to get current action/params for `LocaleLinkGenerator`

---

.github/workflows/php.yml
site/app/Articles/Blog/BlogPostPreview.php
site/tests/Articles/Blog/BlogPostPreviewTest.phpt
site/tests/php-unix.ini

To avoid all blog post preview errors. This test successfully detects all the issues reported in #169.

Write test for `BlogPostPreview::sendPreview()`

---

site/app/Api/Presenters/CompanyPresenter.php
site/app/CompanyInfo/Ares.php
site/app/CompanyInfo/CompanyDetails.php
site/app/CompanyInfo/CompanyInfo.php
site/app/CompanyInfo/RegisterUz.php
site/app/DateTime/DateTimeFormatter.php
site/app/Formatter/TexyFormatter.php
site/app/Makefile/Exceptions/MakefileContainsRealTargetsException.php
site/app/Makefile/Makefile.php
site/app/Pulse/Passwords/SearchResult.php
site/app/Pulse/Presenters/templates/PasswordsStorages/default.latte
site/app/Test/NullLogger.php
site/app/Training/Applications/TrainingApplicationStorage.php
site/app/Training/DateList/trainingApplicationsList.latte
site/app/Training/Dates/TrainingDate.php
site/app/UpcKeys/Technicolor.php
site/app/Www/Presenters/HomepagePresenter.php
site/app/Www/Presenters/TalksPresenter.php
site/psalm.xml
site/tests/Application/BootstrapTest.phpt
site/tests/Articles/ArticlesTest.phpt
site/tests/EasterEgg/WinterIsComingTest.phpt
site/tests/Feed/ExportsTest.phpt
site/tests/Http/SecurityHeadersTest.phpt
site/tests/Media/VideoFactoryTest.phpt
site/tests/Tls/CertificatesTest.phpt
site/tests/Training/FormSpamTest.phpt

Follow-up to #205 but now with enabled dead code detection, making it undead.
Blockers:
- vimeo/psalm#10143 prevents analyzing scripts in `bin/`

Psalm detect unused code

---

site/app/Admin/Presenters/InterviewsPresenter.php
site/app/Admin/Presenters/PresenterTemplates/Interviews/InterviewsDefault.php
site/app/Admin/Presenters/PresenterTemplates/Interviews/InterviewsInterview.php
site/app/Admin/Presenters/TalksPresenter.php
site/app/Admin/Presenters/TrainingsPresenter.php
site/app/Form/TalkSlidesFormFactory.php
site/app/Form/TrainingApplicationMultipleFormFactory.php
site/app/Form/TrainingDateFormFactory.php
site/app/Pulse/Presenters/PasswordsStoragesPresenter.php
site/app/Pulse/Presenters/PresenterTemplates/PasswordsStorages/PasswordsStoragesDefaultTemplate.php
site/app/Training/DateList/UpcomingTrainingDatesListFactory.php
site/app/Training/Dates/TrainingDateInputs.php
site/app/Training/Dates/TrainingDateInputsFactory.php
site/app/UpcKeys/Presenters/HomepagePresenter.php
site/app/Www/Presenters/TrainingsPresenter.php
site/app/Www/Presenters/VenuesPresenter.php

Resolve `PropertyNotSetInConstructor` errors 
By mostly dropping the properties in favor of a method or local variable, or by setting the default property of "current" objects to null.
These will always be initialized in the `action*()` methods and so will always be available in the `createComponent*()` methods. But Psalm can't possibly know that. Still not sure I like it this way, it's there mostly for Psalm only but maybe it's ok.
Resolves errors like
```
ERROR: PropertyNotSetInConstructor - app/Admin/Presenters/TrainingsPresenter.php:44:30 - Property MichalSpacekCz\Admin\Presenters\TrainingsPresenter::$application is not defined in constructor of MichalSpacekCz\Admin\Presenters\TrainingsPresenter or in any private or final methods called in the constructor (see https://psalm.dev/074) …
```

Psalm `PropertyNotSetInConstructor`

---

site/app/Formatter/TexyFormatter.php
site/app/Templating/Filters.php
site/config/common.neon
site/phpstan-latte-templates.neon
site/tests/Formatter/TexyFormatterTest.phpt
site/tests/Templating/FiltersTest.phpt

Enable `strict_types = 1` for compiled Latte templates both for the app, and for the PHPStan Latte tests.
As suggested https://github.com/nette/application/issues/313#issuecomment-1706384973 which I also think is a fairly good idea, given that I write code with `strict_types = 1`, check this and that with PHPStan etc.
And change places that need changing to support that, as reported by the PHPStan Latte extension.

Latte templates with `strict types = 1`

---

site/app/CompanyInfo/CompanyRegisterAres.php
site/app/UpcKeys/Technicolor.php

I had it right in `MichalSpacekCz\Http\HttpStreamContext::create()`, which probably should be used instead, but followed the example in PHP docs that says only `string $message`.
PHP docs PR https://github.com/php/doc-en/pull/2767
Introduced in bd8c0890bd41a4867be17fabdd3966d1d643cf86 in #220

`$message` can be null in `stream_context_set_params()` `notification` callback

---

site/app/CompanyInfo/CompanyRegisterAres.php
site/config/parameters.neon
site/tests/CompanyInfo/CompanyRegisterAresTest.phpt

The new version uses JSON instead of XML.
[The announcement](https://wwwinfo.mfcr.cz/ares/ares_info.html.cz) & [archived](https://web.archive.org/web/20230914225112/https%3A%2F%2Fwwwinfo.mfcr.cz%2Fares%2Fares_info.html.cz)
See https://ares.gov.cz/stranky/vyvojar-info & https://ares.gov.cz/swagger-ui/ for the docs.
This is using the `/ekonomicke-subjekty` endpoint because it returns DIČ/tax id as well.

Support the new ARES (Administrativní registr ekonomických subjektů) version

---

site/app/CompanyInfo/CompanyRegisterAres.php

Resolve Psalm's PossiblyNullOperand - Cannot concatenate with a possibly null|string

---

site/app/Tls/CertificateMonitor.php

I messed it up in #229 commit 780e9a99fb7a3f55e934be4cf739f79435c2009a

Reverse the flag option in certmonitor

---

site/app/UpcKeys/Technicolor.php

Messed up in a5044812575839272c15a544d5b0dcf2e389e0cc PR #229 because this code is not tested, unfortunately.

preg_match() always returns the full string at offset 0, ignore it

---

site/app/Formatter/TexyFormatter.php
site/app/Talks/TalkSlides.php
site/app/Utils/Hash.php
site/app/Www/Presenters/ExportsPresenter.php
site/disallowed-calls.neon

xxHash is much faster than MD5 or SHA-1 which in these cases were used to favor speed over security which wasn't an issue anyway. xxHash is even faster than MurmurHash3.
https://php.watch/versions/8.1/xxHash
https://xxhash.com/

Use xxHash to hash text for non-cryptographic purposes

---

.github/workflows/php-tester-include-skipped.yml
site/Makefile
site/app/CompanyInfo/CompanyRegisterAres.php
site/app/Test/TestCaseRunner.php
site/disallowed-calls.neon
site/phpstan-vendor.neon
site/tests/CompanyInfo/CompanyRegisterAresTest.phpt
site/tests/CompanyInfo/CompanyRegisterRegisterUzTest.phpt

I don't understand why but for this 'res' source, the country code is returned as "1", yes a string, instead of "cz", so let's deal with that. This wasn't happening when I've build the support in #225.
It could be easily removed in the future, and there's a test for it (the one for the company with id 00256081), so if it is removed and it shouldn't be, I should know about it rather soon.
Fix #242
The test querying the service is marked as "skipped" because it uses the Internet to actually query the live service and I don't want to query it when I'm running my tests in dev env for example. But I'd like to run the tests someday, so I've introduced a way to run all skipped tests, just define an environment variable `TEST_CASE_RUNNER_INCLUDE_SKIPPED=1` and run the test case again. Will also …

ARES country "upgrade"

---

site/app/Admin/Presenters/templates/Trainings/date.latte
site/app/EasterEgg/Presenters/templates/Nette/nette.micro-ifconfig.latte
site/app/Pulse/Presenters/templates/PasswordsStorages/default.latte
site/app/Pulse/Presenters/templates/PasswordsStorages/rating.latte
site/app/Pulse/Site.php
site/app/Pulse/WildcardSite.php
site/app/Training/DateList/trainingApplicationsList.latte
site/app/Www/Presenters/templates/Trainings/reviews.latte
site/bin/latte-lint.php
site/config/common.neon
site/tests/Pulse/Passwords/PasswordsTest.phpt

Has to be enabled with `$latteEngine->setStrictParsing()` because when enabled in new Linter with the strict param, it's only used when no custom engine is passed.
Close #241

Latte strict parsing mode

---

.github/workflows/securitytxt.yml

Indeed:
```
==> Setup PHP
✓ PHP Installed PHP 8.3.0
==> Setup Extensions
✓ gnupg Installed and enabled
```
Revert "Don't run the security.txt check on PHP 8.3, ext-gnupg is not yet available"
This reverts commit c141bf0bccc3a1961d754c2ee3e35cb439c5cbe5 #163

Run the security.txt check on PHP 8.3 again, ext-gnupg is available

---

site/phpcs.xml

They're not checked here with the code sniffer but let's follow what's used elsewhere.
Follow-up to #111

Remove duplicated spaces in XML

---

site/app/Test/PrivateProperty.php
site/app/User/Manager.php
site/config/tests.neon
site/tests/User/ManagerTest.phpt

Resolves
```
------ -------------------------------------------------------
Line   app/User/Manager.php
------ -------------------------------------------------------
129    Unreachable statement - code above always terminates.
------ -------------------------------------------------------
```
which happens because nette/database 3.2.0 added `never` return type to Row::__get().
This way, PhpStorm complains "Return value must be of type 'int', 'never' returned" but PHPStan doesn't, so...

The `userId` property is normalized to int so no need to type-cast it

---

conf/nginx/dev-php.conf
conf/php/dev-michalspacek.cz.conf
site/app/Application/Bootstrap.php
site/composer.json
site/composer.lock
site/tests/Application/BootstrapTest.phpt
site/vendor/composer/installed.json
site/vendor/composer/installed.php
site/vendor/spaze/sri-macros/src/Config.php

Use and create extra temp dirs for CLI & tests to avoid permissions issues when some files in cache are created by the web server, and they'd need to be overwritten by tests for example.
Revert "Move temp dir to WSL filesystem because using `/mnt` is slow"
This basically reverts commit 2f41049 #88

Moving the whole repo inside the WSL file system

---

site/public/www.michalspacek.cz/i/css/screen.css
site/public/www.michalspacek.cz/i/js/scripts.js

On mobiles, there's no way to display the `ABBR` `title` attribute. So let's create one way.
Heavily inspired by this https://bitsofco.de/making-abbr-work-for-touchscreen-keyboard-mouse/ and a bit by this https://stackoverflow.com/a/69353021/10537872
The relevant changes are that the title is read from the `data-title` attribute, which is created on mouseover from the regular `title` attribute which is then removed and added back on mouseout. Trying to keep the original attribute there for screen readers etc.
On mouseout, the `blur()` method is also called which "cancels" the focus state, in which the element is when it was clicked on. Without this, if you clicked the ABBR tag on desktop, the title would be visible until you've clicked again somewhere.
JS is also used to add `tabindex=0` …

Display a custom `ABBR` `title` which also works on mobiles

---

site/app/Application/WebApplication.php
site/app/EasterEgg/CrLfUrlInjections.php
site/app/Test/Http/Response.php
site/config/services.neon
site/disallowed-calls.neon
site/tests/Application/ThemeTest.phpt
site/tests/EasterEgg/CrLfUrlInjectionsTest.phpt

URLs like `/%0DSet-Cookie:...` would throw
> PHP Warning: Header may not contain more than a single header, new line detected in [...]Http/Response.php:98
because of the `IResponse::redirect()` call in `WebApplication::redirectToSecure()`:
https://github.com/spaze/michalspacek.cz/blob/73b82f274771460ab6252d4c0b2961a226a5423d/site/app/Application/WebApplication.php#L40
Let's detect such attempts and stop them in their tracks.

Detect CRLF URL attempts and fight back with an attempted humor 

---

.github/workflows/composer-vulns.yml

The file is created in `/tmp` but anyway, I think the cache action cannot access the file inside the Docker container.
See my comment here https://github.com/symfonycorp/security-checker-action/issues/11#issuecomment-1939390503

Don't use cache for the Symfony security check

---

site/composer.lock
site/vendor/composer/installed.json
site/vendor/composer/installed.php
site/vendor/spaze/phpinfo/src/PhpInfo.php

To support pure numerical session ids in sanitization
Follow-up to #288 #289

Update spaze/phpinfo to the re-released v1.1.0

---

site/config/local.template.neon

With an empty directive, Chrome will show this in devtools console: "'require-trusted-types-for' Content Security Policy directive is empty; The directive has no effect."
Ref #149

Don't require Trusted Types in dev

---

site/app/DependencyInjection/DiServices.php
site/composer-dependency-analyser.php
site/config/services.neon
site/tests/DependencyInjection/DiServicesTest.phpt

Otherwise if the service is created by the DI container, the analyzer logs "headers already sent" because it echoes that it's using the config file, and then in the config file, the DI container would try to set the `zlib.output_compression` to yes when created, which emits a header, or tries to in CLI, which generates the error.
Follow-up to #286

Get all classes for the dependency analyzer statically

---

site/config/contentsecuritypolicy.neon

This doesn't seem to change much, and even if it would, it would still be the same as not having the hash here.
The CSS added here: https://github.com/nette/forms/blob/ec3c6598b9f27e8787961f2b02e12a477994bf3b/src/assets/netteForms.js#L319C22-L319C161

Add hash of CSS added by netteForms.js to style the dialog element with form errors

---

site/app/Form/PostFormFactory.php
site/public/www.michalspacek.cz/i/js/admin.js

The Nette JS validation is triggered on form submit but at that moment, the button caption is already changed to "loading" by the click event handler. But because the preview frame never loads then, the "loading" caption would stay.
So we'll observe any child list changes of the BODY element and see if there's a form validation DIALOG element, and if yes, revert the caption.
Also revert it after 5 secs, just in case.

Revert "loading" caption on blog preview error

---

.github/dependabot.yml
.github/workflows/codeql.yml
.github/workflows/composer-vulns.yml
.github/workflows/gitleaks.yml
.github/workflows/php-latte.yml
.github/workflows/php-tester-include-skipped.yml
.github/workflows/php.yml
.github/workflows/scorecard.yml
.github/workflows/securitytxt.yml
.github/workflows/tls.yml

I've added the OpenSSF Scorecards GitHub Action in #307 and that has generated quite some alerts. And this PR resolves them.
Close #308
Close #309
Close #310

Resolve security alerts, at least most of them

---

.github/workflows/codeql.yml

It already has the job-level permissions set.
Close #313

Add top level read permission to CodeQL config

---

.github/dependabot.yml

Hopefully it does what it says on the tin, and that's also updating the files in the vendor folder.
Dependabot composer updates config added in #315

Tell Dependabot to vendor dependencies when updating them

---

.github/workflows/codeql.yml

> * site/vendor/tracy/tracy/src/Tracy/Dumper/assets/dumper.js#L354C86:86: A parse error occurred: `Comma is not permitted after the rest element`. Check the syntax of the file. If the file is invalid, correct the error or [exclude](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/customizing-code-scanning) the file from analysis.
https://github.com/spaze/michalspacek.cz/actions/runs/8996895829/job/24714088773#step:5:918
CodeQL config added in #311

CodeQL reports a rest element but that's a spread syntax in the `dumper.js` file

---

.github/dependabot.yml

Revert "Tell Dependabot to vendor dependencies when updating them" 
It doesn't seem to do what I thought it would do, at least for Composer, it doesn't actually download the changed files.
This reverts commit cf3d5dc #318
I check NPM and Composer usually manually (`npm outdated`, `composer outdated`), often weekly, sometimes more often.
Keep GitHub actions weekly, as that I don't check manually because I don't if that's even possible.

Run Dependabot updates monthly for NPM and Composer, as a last resort 

---

site/app/Articles/Articles.php
site/app/Articles/Blog/BlogPostFactory.php
site/app/Articles/Blog/BlogPostPreview.php
site/app/Form/PostFormFactory.php
site/app/Formatter/TexyFormatter.php
site/tests/Articles/ArticlesTest.phpt
site/tests/Articles/Blog/BlogPostPreviewTest.phpt
site/tests/Formatter/TexyFormatterTest.phpt

It's been cached when the `BlogPost` object was created before it was sent to `sendPreview()` (where caching was disabled a little bit too late), and also in `onValidate` where we still want the data to be validated (so can't call `setValidationScope([])`). The original `BlogPost` object is still cached in `actionEdit()`, but that's the original one. not the previewed one.

Don't cache blog post previews

---

.github/workflows/php.yml
site/Makefile
site/app/Admin/Presenters/templates/@layout.latte
site/app/Pulse/Presenters/templates/@layout.latte
site/app/UpcKeys/Presenters/templates/Homepage/default.latte
site/app/Www/Presenters/templates/@layout.latte
site/app/Www/Presenters/templates/Pgp/default.latte
site/bin/check-sri-macros-concat.sh

Check and make sure that spaze/sri-macros concatenated resources (e.g. `{script foo + bar}`) use spaces around the plus sign.
This is needed because in [Latte 3.0.17](https://github.com/nette/latte/releases/tag/v3.0.17), unquoted strings can contain `+` but if it's specified as ` + `, with spaces, then the previous behavior works too.
I've added tests in spaze/sri-macros#26, otherwise no change wasn't needed in that package.
Follow-up to #365

Correct spaze/sri-macros concatenations

---

site/app/Formatter/Placeholders/FetchMetadataTexyFormatterPlaceholder.php
site/app/Formatter/Placeholders/TexyFormatterPlaceholder.php
site/app/Formatter/Placeholders/TrainingDateTexyFormatterPlaceholder.php
site/app/Formatter/TexyFormatter.php
site/app/Formatter/TexyPhraseHandler.php
site/app/Http/FetchMetadata/FetchMetadata.php
site/app/Http/FetchMetadata/FetchMetadataHeader.php
site/app/Test/Http/Request.php
site/config/services.neon
site/psalm.xml
site/tests/Formatter/TexyFormatterTest.phpt
site/tests/Http/FetchMetadata/FetchMetadataTest.phpt

So I can add live metadata to blog posts (more like to just one blog post) with placeholders like
```
/---
**FETCH_METADATA:all**
**FETCH_METADATA:Sec-Fetch-Dest**
\---
```
or
```
''**FETCH_METADATA:Sec-Fetch-Dest**''
```
etc.

Add FetchMetadata service and a placeholder

---

site/app/Api/Presenters/CompanyPresenter.php
site/app/Application/WebApplication.php
site/app/Http/FetchMetadata/ResourceIsolationPolicy.php
site/app/Http/FetchMetadata/ResourceIsolationPolicyCrossSite.php
site/app/lang/messages.cs_CZ.neon
site/app/lang/messages.en_US.neon
site/config/services.neon
site/tests/Http/FetchMetadata/ResourceIsolationPolicyTest.phpt

AKA block most cross-site requests to block some attacks
For now in report-only mode as configured in `services.neon`.
See https://web.dev/articles/fetch-metadata#implementing_a_resource_isolation_policy
and my upcoming article about Fetch Metadata.

Add Resource Isolation Policy using Fetch Metadata

---

site/app/Www/Presenters/ExportsPresenter.php

Some RSS readers also send `Sec-Fetch-*` headers, I think Thunderbird is one of them.
Follow-up to #371

RSS/Atom exports can also be requested cross-site

---

app/Makefile
app/bin/xmllint.sh

Actions are crashing because of it, used in XML linter action to install `xmllint` which is used to validate `phpcs.xml`.
Introduced in #122.

Ubuntu 24.04 in GitHub actions doesn't contain apt-fast, stop using it

---

.gitleaks.toml
.gitleaksignore
app/Makefile

Gitleaks scheduled scan started finding new findings some time ago breaking my scheduled scans. So I've ignored the `vendor` dir because no real secrets in there, and updated one commit hash.

Gitleaks updates

---

app/Makefile
app/bin/colors.sh
app/bin/update-security.txt.sh
app/public/upcwifikeys.com/.well-known/security.txt
app/public/www.michalspacek.com/.well-known/security.txt
app/public/www.michalspacek.cz/.well-known/security.txt

Using `make update-security-txt` because now I have a script for that!
Just to restate, the new date is less than a year/365 days into the future because the spec says that it is recommended that the value be [less than a year](https://www.rfc-editor.org/rfc/rfc9116#section-2.5.5-1) so this would generate a warning if it would be more, and when running my `security.txt` checker in strict mode, the warning would turn into an error.

Update the `Expires` date in security.txt files

---

app/config/services.neon
app/src/Admin/Presenters/BasePresenter.php
app/src/Admin/Presenters/templates/@layout.latte
app/src/Api/Presenters/BasePresenter.php
app/src/Api/Presenters/CertificatesPresenter.php
app/src/Api/Presenters/CompanyPresenter.php
app/src/EasterEgg/FourOhFourButFound.php
app/src/EasterEgg/templates/etcPasswd.html
app/src/Http/Robots/Robots.php
app/src/Http/Robots/RobotsRule.php
app/src/Pulse/Presenters/ErrorPresenter.php
app/src/Www/Presenters/TrainingsPresenter.php
app/src/Www/Presenters/templates/Trainings/files.latte
app/tests/Http/Robots/RobotsTest.phpt

Pages that should not be indexed, should use the header or a meta tag, not robots.txt, but we'll try both at least for now.
https://support.google.com/webmasters/answer/7440203#indexed_though_blocked_by_robots_txt
https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag

Send `X-Robots-Tag` header in all admin/api controllers and in pulse error 

---

app/public/www.michalspacek.cz/i/css/screen.css

Because Safari 15.8 doesn't support it and while newer ones do, this is easy to change.
Introduced in #265

Unwrap the `text-decoration` CSS shorthand

---

app/config/services.neon
app/public/www.michalspacek.cz/i/css/upc/screen.css
app/src/Http/Client/HttpClient.php

Use `TypedDatabase` with non-default connection for `Technicolor` keys

---

.github/workflows/gitleaks.yml

The bugfix has been merged but wasn't included in the [8.22.0 release](https://github.com/gitleaks/gitleaks/releases/tag/v8.22.0), waiting for the new version, then this can be reverted.

Disable Gitleaks artifact upload because of a bug in Gitleaks

---

.github/workflows/codeql.yml
.github/workflows/php-tester-include-skipped.yml
.github/workflows/php.yml
.github/workflows/scorecard.yml
.github/workflows/tls.yml
app/composer.lock
app/vendor/composer/InstalledVersions.php
app/vendor/composer/autoload_psr4.php
app/vendor/composer/autoload_static.php
app/vendor/composer/installed.json
app/vendor/composer/installed.php

- Bump actions/upload-artifact from 4.4.3 to 4.5.0
- Bump github/codeql-action from 3.27.9 to 3.28.0
- roave/security-advisories updated from dev-latest@4aa68d3 to dev-latest@5a88337
See changes: https://github.com/Roave/SecurityAdvisories/compare/4aa68d3...5a88337

Update packages & actions

---

.github/workflows/gitleaks.yml

Gitleaks [8.22.1](https://github.com/gitleaks/gitleaks/releases/tag/v8.22.1) release contains the fix ("generate report file even if no findings") so this can be reverted.
Reverts spaze/michalspacek.cz#450

Revert "Disable Gitleaks artifact upload because of a bug in Gitleaks"

---

app/config/common.neon
conf/nginx/common-php.conf
conf/php/dev-michalspacek.cz.conf
conf/php/prod-michalspacek.cz.conf

Run on PHP 8.4.
Also stop using the [deprecated](https://wiki.php.net/rfc/deprecations_php_8_4#sessionsid_length_and_sessionsid_bits_per_character) `session.sid_length` and `session.sid_bits_per_character` config options.

Upgrade to PHP 8.4

---

.github/workflows/php-tester-include-skipped.yml
.github/workflows/php.yml
.github/workflows/securitytxt.yml
.github/workflows/tls.yml

Tests using 8.3 removed except Psalm which is not ready for PHP 8.4 yet, see #439

Stop testing on PHP 8.3 except Psalm

---

app/Makefile

This requires me to keep the following packages in my dev, some are for Psalm itself, others allow it to analyze the code base:
php8.3-cli
php8.3-common
php8.3-intl
php8.3-mbstring
php8.3-opcache
php8.3-readline
php8.3-xml
They can be removed once Psalm supports PHP 8.4 (#439), or when I stop using it.

Run Psalm on PHP 8.3

---

app/config/common.neon
app/config/services.neon
app/psalm.xml
app/src/Application/Locale/LocaleLinkGenerator.php
app/src/Application/Routing/LocaleRouter.php
app/src/Application/Routing/RouterFactory.php
app/tests/Application/Locale/LocaleLinkGeneratorTest.phpt

See the [blog post](https://blog.nette.org/en/one-line-in-configuration-will-speed-up-your-nette-application-how-is-that-possible).
The speedup is tiny in my case, if any at all, as the database connection is already created on-demand only (since 7766444 #14) but it generally seems like a good idea.
Needed a bit of a refactoring because `RouterFactory::getLocaleRouters()` returned an empty list in tests when the lazy mode was enabled because `RouterFactory::createRouter()` has not been called yet.

Enable nette/di lazy mode

---

.gitleaks.toml

And uses it instead of `[rules.allowlist]` which still works.
https://github.com/gitleaks/gitleaks/releases/tag/v8.23.0

Gitleaks has added `[[rules.allowlists]]`

---

app/config/services.neon
app/src/Form/FormValidators.php
app/src/Form/PostFormFactory.php
app/src/Form/TalkFormFactory.php
app/src/Form/TalkSlidesFormFactory.php
app/src/lang/messages.cs_CZ.neon
app/src/lang/messages.en_US.neon
app/tests/Form/FormValidatorsTest.phpt

Validation rules added using the `addRule(Form::Pattern, ...)` call, not using any custom validation callback because I want the JS validation to be also used and don't want to add a custom one.

Validate slug/action/alias name

---

app/disallowed-calls.neon
app/src/EasterEgg/FourOhFourButFound.php
app/src/EasterEgg/templates/phpCve20244577.html
app/src/Form/FormValidators.php
app/src/Www/Presenters/BasePresenter.php
app/src/Www/Presenters/ErrorPresenter.php
app/src/lang/messages.cs_CZ.neon
app/src/lang/messages.en_US.neon
app/tests/EasterEgg/FourOhFourButFoundTest.phpt

Requests for `/etc/passwd` will now trigger _zi egg_ even on non-404 pages (think `/?file=/etc/passwd` where `/` is a regular existing page) and also on PHP CGI CVE-2024-4577 😈

Show some serious content for more exploit attempts

---

.gitleaks.toml

It was added in #76 to detect "dev" and "prod" keys, but I've since started to use prefixed encryption keys in #269 so the custom rule is not needed anymore. This is why you use prefixed keys, it makes things simple, and I like making things simple.
Also, the custom generic rule started throwing many false positives after I've upgraded to Gitleaks 8.23.1 for some reason.

Remove the custom generic Gitleaks rule as it's not needed anymore

---

.github/workflows/codeql.yml
.github/workflows/php-tester-include-skipped.yml
.github/workflows/php.yml
.github/workflows/scorecard.yml
.github/workflows/tls.yml

- actions/cache from 4.2.0 to 4.2.1 
- actions/upload-artifact from 4.6.0 to 4.6.1 
- github/codeql-action from 3.28.9 to 3.28.10 
- ossf/scorecard-action from 2.4.0 to 2.4.1

Bump GitHub Actions

---

app/src/EasterEgg/FourOhFourButFound.php
app/tests/EasterEgg/FourOhFourButFoundTest.phpt

In #471 I have added support to show Easter eggs also on URLs like `/?file=/etc/passwd` but that "inherited" the status code of the `/` page, didn't show 404.
Also in the Pulse module, due to the URL routing, even `/etc/passwd` returned 200, this will "fix" it.

Always send 404 in this Easter egg

---

app/src/Form/ThemeFormFactory.php

The CSRF protection requires session so session was started for each and every website visit, which added a row in the sessions table. That's unnecessary.
Follow-up to #381

Don't use CSRF protection for the light/dark mode switch form

---

app/public/www.michalspacek.cz/i/css/screen.css
app/src/Admin/Presenters/templates/Homepage/default.latte
app/src/Tls/Certificate.php
app/src/Tls/CertificateFactory.php
app/src/Tls/Certificates.php
app/src/Tls/CertificatesApiClient.php
app/src/Tls/OpenSsl.php
app/src/Tls/OpenSslX509ParseResult.php
app/tests/Tls/CertificateFactoryTest.phpt
app/tests/Tls/CertificatesTest.phpt
app/tests/Tls/OpenSslTest.phpt

Some certs may be missing the CN field (when issued with for example the Let's Encrypt's tlsserver [profile](https://letsencrypt.org/docs/profiles/)) so it's nice if I could tell which certificate is which.
The SAN field will be populated gradually as the Certbot hook (#542) reports them over the next few months.

Display HTTPS certs' CN and SAN in admin

---

app/config/services.neon
app/src/Application/WebApplication.php
app/src/User/UserSessionAdditionalData.php
app/tests/User/UserSessionAdditionalDataTest.phpt

Because when the session is regenerated, the old one is deleted in `Nette\Http\Session::regenerateId()`, which means the whole row is deleted in `Spaze\Session\MysqlSessionHandler::destroy()` and then when a new row is inserted again, it doesn't have the user id, because it was set only in logged in/out event handlers.
Follow-up to #549

Set the session handler additional data (i.e. user id) whenever available

---

app/bin/clean_sessions.php

Due to the database session handler, this has to be handled manually, the session cleaner which comes prepackaged with the PHP packages won't handle it.

A script to clean old stale session rows

---

conf/nginx/prod-https-admin.michalspacek.cz.conf
conf/nginx/prod-https-upc.michalspacek.cz.conf
conf/nginx/prod-michalspacek.cz.conf

The idea is to have a certificate that covers `admin.m(ichalspacek).c(z)`, another one that covers `www.m.c`, and another one that's used for the old redirected subdomains (like `upc.m.c` and `heartbleed.m.c`). Some subdomains are duplicated across multiple certificates to leverage HTTP/2's certificate validation that's skipped if the cert covers the target subdomain and the DNS resolves to the same IP as the currently loaded URL.

Split the cert to smaller certs

---

app/src/Presentation/Api/Certificates/CertificatesPresenter.php

This may happen for example when the certificate file reported with the hook doesn't exist because I've made a typo when calling the hook manually, or something like that.

Handle empty certificates in the HTTPS certificate logger

---

app/config/contentsecuritypolicy.neon

The CSP integrity reporting feature seems to be available only for scripts, see https://chromestatus.com/feature/6337535507431424
This reverts commit 989c9bef7e096429fcdf972705cbaf51b13045b0 of #593

Revert "Add CSP integrity reports to CSS/style-src as well"
